# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TasksManager', '0003_auto_20161212_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TasksManager.Developer', verbose_name='User'),
        ),
    ]
